-- DROP TABLE IF EXISTS public.insurance;

CREATE TABLE IF NOT EXISTS public."insurance"
(
    "insuranceID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "PatientRecordNumber" bigint NOT NULL,
	"providerName" character varying COLLATE pg_catalog."default" NOT NULL,
	"policyNumber" character varying COLLATE pg_catalog."default" NOT NULL,
	
    CONSTRAINT insurance_pkey PRIMARY KEY ("insuranceID"),
	CONSTRAINT fk_patient FOREIGN KEY ("PatientRecordNumber")
	    REFERENCES public."patient" ("PatientRecordNumber") MATCH SIMPLE
	    ON UPDATE NO ACTION
	    ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.insurance
    OWNER to postgres;